package main.java.nasaTestSuite;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.Text;
import org.jdom2.input.SAXBuilder;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

import test.java.FullTest;

/**
 *
 * @author WoodmDav
 */
public class GUI extends javax.swing.JFrame {
	private boolean running = true;
    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
        jRadioAndroid.setSelected(true);
        jCheckRac.setSelected(true);
        jCheckStrombo.setSelected(true);
        jCheckDehum.setSelected(true);
        
        //Generated:
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jCheckRac = new javax.swing.JCheckBox();
        jCheckStrombo = new javax.swing.JCheckBox();
        jCheckDehum = new javax.swing.JCheckBox();
        jRadioAndroid = new javax.swing.JRadioButton();
        jRadioIphone = new javax.swing.JRadioButton();
        jCheckSignIn = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckRac.setText("RAC");
        jCheckRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRacActionPerformed(evt);
            }
        });

        jCheckStrombo.setText("Stromboli");
        jCheckStrombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckStromboActionPerformed(evt);
            }
        });

        jCheckDehum.setText("Dehumidifier");
        jCheckDehum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDehumActionPerformed(evt);
            }
        });

        jRadioAndroid.setText("Android");
        jRadioAndroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAndroidActionPerformed(evt);
            }
        });

        jRadioIphone.setText("iPhone");
        jRadioIphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioIphoneActionPerformed(evt);
            }
        });

        jCheckSignIn.setText("Sign In");

        jLabel1.setText("Automated Testing Configuration");

        jButtonGo.setText("GO");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioAndroid)
                            .addComponent(jRadioIphone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckRac)
                            .addComponent(jCheckStrombo)
                            .addComponent(jCheckDehum)
                            .addComponent(jCheckSignIn)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGo)
                        .addGap(26, 26, 26)))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jCheckRac)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckStrombo)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckDehum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckSignIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jButtonGo)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioAndroid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioIphone)
                        .addContainerGap(168, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    private void jCheckDehumActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jCheckStromboActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jCheckRacActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jRadioAndroidActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jRadioIphone.setSelected(false);
    }                                             

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {      
    	System.out.println("Go Pressed");
        writeXML(jRadioAndroid.isSelected(), jRadioIphone.isSelected(), jCheckStrombo.isSelected(), jCheckRac.isSelected(), jCheckDehum.isSelected(), jCheckSignIn.isSelected());
        running = false;
//        while(!FullTest.fakeNotify) {}
        System.out.println("Exiting GUI");
//        System.exit(0);
        this.dispose();
        
    }                                         

    private void jRadioIphoneActionPerformed(java.awt.event.ActionEvent evt) {                                             
        jRadioAndroid.setSelected(false);
    }                                            

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JCheckBox jCheckDehum;
    private javax.swing.JCheckBox jCheckRac;
    private javax.swing.JCheckBox jCheckSignIn;
    private javax.swing.JCheckBox jCheckStrombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioAndroid;
    private javax.swing.JRadioButton jRadioIphone;
    // End of variables declaration                   

    //Eclipse

	
	private static void writeXML(boolean isAndroid, boolean isIphone, boolean stromboChecked, boolean racChecked, boolean dehumChecked, boolean signInChecked){
        try{	
            Document doc = new Document();				
            Element theRoot = new Element("config");
            doc.setRootElement(theRoot);

            Element iphone= new Element("iphone");
            Element android= new Element("android");
            Element rac = new Element("rac");
            Element strombo = new Element("strombo");
            Element dehum = new Element("dehum");
            Element signIn = new Element("sign-in");
            //text within
            iphone.addContent(new Text(String.valueOf(isIphone)));
            android.addContent(new Text(String.valueOf(isAndroid)));
            rac.addContent(new Text(String.valueOf(racChecked)));
            strombo.addContent(new Text(String.valueOf(stromboChecked)));
            dehum.addContent(new Text(String.valueOf(dehumChecked)));
            signIn.addContent(new Text(String.valueOf(signInChecked)));
            //Add to root		
            theRoot.addContent(android);
            theRoot.addContent(iphone);
            theRoot.addContent(rac);
            theRoot.addContent(strombo);
            theRoot.addContent(dehum);
            theRoot.addContent(signIn);

            // Uses indenting with pretty format
            XMLOutputter xmlOutput = new XMLOutputter(Format.getPrettyFormat());

            // Create a new file and write XML to it

//            xmlOutput.output(doc, new FileOutputStream(new File("/src/main/resources/config2.xml")));

            xmlOutput.output(doc, new FileOutputStream(new File("C:\\Users\\WoodmDav\\localDocuments\\myCode\\GIT\\Nasa Test Engine 1\\Nasa Test Engine 1\\src\\main\\resources\\config.xml")));

            
            System.out.println("Wrote to file");

        }catch (Exception e) {

            System.out.println(e);
        }
	}
	public boolean isRunning() {
		return running;
	}
}
